Repository GlueOps/gatekeeper, pull requests merged in 2024-10, with the labels that each got.

#2 feat: initial commit
  .github/workflows/container_image.yaml
  Dockerfile
  README.md
  main.py
  requirements.txt
Labels: documentation, enhancement, Review effort [1-5]: 3

#3 feat: adding health check
  main.py
Labels: Review effort [1-5]: 1

#4 fix: README.md as it was missing a few steps
  README.md
Labels: documentation, Review effort [1-5]: 1
